src:=html
srcauth:=html/auth
srcinc:=includes

all: html includes auth

html:
	scp -r \
	$(src)/* hschang@proj-309-10.cs.iastate.edu:/var/www/html

ssh-309server:
	ssh hschang@proj-309-10.cs.iastate.edu

